### PR TITLE
Swift 3 Support

### PR DESCRIPTION
**Pull request by Eke**
Added swift 3 support

### CODE REVIEW

**Comment by sgl0v** [comment]
Well done! Could you please squash commits & update the version in the `SCrypto.podspec` file to 2.0.0 ?

**Comment by Eke** [comment]
Sure ! will do it today later

**Comment by Eke** [comment]
@sgl0v squashed and updated to 2.0.0

**Comment by Eke** [comment]
Hello @sgl0v ! Any updates about PR?

**Pull request merged**
